MyStories.Web/Controllers/GroupController.cs
using System.Web.Mvc;
using MyStories.Entities.Models;
using MyStories.Service;
using Repository.Pattern.UnitOfWork;
using MyStories.Web.Helpers;

namespace MyStories.Web.Controllers
{
    public class GroupController : Controller
    {
        private readonly IStoredProcedureService _storedProcedureService;
        private readonly IGroupService _groupService;
        private readonly IUnitOfWorkAsync  _unitOfWork;
        
         public GroupController(
            IUnitOfWorkAsync unitOfWork,
            IStoredProcedureService storedProcedureService,
            IGroupService groupService)
        {
            _unitOfWork = unitOfWork;
            _groupService = groupService;
            _storedProcedureService = storedProcedureService;
        }
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult GetGroupDetails()
        {
            return Json(_storedProcedureService.GetGroupDetails(), JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult SaveGroup(Group group)
        {
            var result = _groupService.SaveGroup(_unitOfWork, group);
            return Json(result.HasError ? ModelActionResult.GetNotSuccessed(result.Message) : ModelActionResult.GetSuccessed(group.Id, "Group was successfully saved!"), JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var result = _groupService.DeleteGroup(_unitOfWork, id);
            return Json(result.HasError ? ModelActionResult.GetNotSuccessed(result.Message):  ModelActionResult.GetSuccessed("Group was successfully deleted!"), JsonRequestBehavior.AllowGet);
        }
    }
}

MyStories.Web/Controllers/StoryController.cs
using MyStories.Service;
using Repository.Pattern.UnitOfWork;
using System.Web.Mvc;
using MyStories.Entities.Models;
using System.Linq;
using Microsoft.AspNet.Identity;
using MyStories.Entities.Assitants;
using MyStories.Web.Helpers;

namespace MyStories.Web.Controllers
{
    public class StoryController : Controller
    {
        private readonly IStoryService _storyService;
        private readonly IUnitOfWorkAsync  _unitOfWork;
        
         public StoryController(
            IUnitOfWorkAsync unitOfWork,
            IStoryService storyService)
        {
            _unitOfWork = unitOfWork;
            _storyService = storyService;
        }
        
        //
        // GET: /Story/
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult GetMyStories(JqxGridSentData jqxGridData)
        {
            var a = new { Rows = _storyService.GetMyStories(jqxGridData, User.Identity.GetUserId()).ToList(), TotalRows = jqxGridData.totalrows };
            return Json(a, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetStory(int id)
        {
            return Json(_storyService.FindStory(id), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetAllGroups()
        {
            return Json(_storyService.GetAllGroupNameValues(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult SaveStory(Story story)
        {
            if (!ModelState.IsValid)
            {
               return Json(ModelActionResult.GetNotValid("Model is not valid!"), JsonRequestBehavior.AllowGet);
            }

            story.UserId = User.Identity.GetUserId();
            var result = _storyService.SaveStory(_unitOfWork, story);

            return Json(result.HasError ? ModelActionResult.GetNotSuccessed(result.Message) : ModelActionResult.GetSuccessed("Story was successfully saved!"), JsonRequestBehavior.AllowGet);
        }
        
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var result = _storyService.DeleteStory(_unitOfWork, id);
            return Json(result.HasError ? ModelActionResult.GetNotSuccessed(result.Message) : ModelActionResult.GetSuccessed("Story was successfully saved!"), JsonRequestBehavior.AllowGet);
        }
    }
}

MyStories.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!-- #FAVICONS -->
    <!-- ================== BEGIN BASE CSS STYLE ================== -->
    <link href="~/Content/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css/myStories.css" rel="stylesheet" />
    <link href="~/Content/jqx.base.css" rel="stylesheet" />
    <link href="~/Content/jqx.Story.css" rel="stylesheet"/>
    <link href="~/Content/parsley.css" rel="stylesheet" />

    <!-- ================== END PAGE LEVEL STYLE ================== -->
    <script type="text/javascript" src="~/Scripts/jquery-2.1.3.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery-ui.min.js"></script>
    <script type="text/javascript" src="~/Scripts/globalization/globalize.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if(this.Request.IsAuthenticated)
                    { 
                    <li>@Html.ActionLink("My Stories", "Index", "Story")</li>
                    <li>@Html.ActionLink("Groups", "Index", "Group")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
<div class="container body-content">
    <div id="dvMsgs">
        <div id="successAlert" class="hide alert alert-success">
            <span class="close" onclick="$('#successAlert').hide()">&times;</span>
            <strong id="strSuccess">Success! </strong><span id="successMSG"></span>
        </div>
        <div id="errorAlert" class="hide alert alert-danger">
            <span class="close" onclick="$('#errorAlert').hide()">&times;</span>
            <strong>Error! </strong><span id="errorMSG"></span>
        </div>
    </div>
    <div class="bodyContainer">
        @RenderBody()
    </div>
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year</p>
    </footer>
</div>
<script type="text/javascript">
    var loggedUserId = '@User.Identity.GetUserId()';
</script>
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
        <!-- ================== BEGIN BASE JS ================== -->
        <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jqx-all.js"></script>
    <script src="~/Scripts/parsley.js"></script>

    <script type="text/javascript" src="~/Content/js/Layout.js"></script>
    <!-- ================== END PAGE LEVEL JS ================== -->
</body>
</html>